export const GET_ACCOUNT_USERS_START = 'GET_ACCOUNT_USERS_START';
export const GET_ACCOUNT_USERS = 'GET_ACCOUNT_USERS';
export const GET_ACCOUNT_USERS_ERROR = 'GET_ACCOUNT_USERS_ERROR';

export const REFRESH_ACCOUNT_USERS_START = 'REFRESH_ACCOUNT_USERS_START';
export const REFRESH_ACCOUNT_USERS = 'REFRESH_ACCOUNT_USERS';
export const REFRESH_ACCOUNT_USERS_ERROR = 'REFRESH_ACCOUNT_USERS_ERROR';
