export const LOGIN_START = 'LOGIN_START';
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER = 'REGISTER';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const UPDATE_LOGGED_USER_START = 'UPDATE_LOGGED_USER_START';
export const UPDATE_LOGGED_USER = 'UPDATE_LOGGED_USER';
export const UPDATE_LOGGED_USER_ERROR = 'UPDATE_LOGGED_USER_ERROR';

export const GET_LOGGED_USER_START = 'GET_LOGGED_USER_START';
export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const GET_LOGGED_USER_ERROR = 'GET_LOGGED_USER_ERROR';
