export const GET_TAGS_START = 'GET_TAGS_START';
export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';

export const REFRESH_TAGS_START = 'REFRESH_TAGS_START';
export const REFRESH_TAGS = 'REFRESH_TAGS';
export const REFRESH_TAGS_ERROR = 'REFRESH_TAGS_ERROR';
