export const LOGIN_START = 'LOGIN_START';
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const UPDATE_LOCALE_START = 'UPDATE_LOCALE_START';
export const UPDATE_LOCALE = 'UPDATE_LOCALE';
export const UPDATE_LOCALE_ERROR = 'UPDATE_LOCALE_ERROR';

export const UPDATE_USER_DETAILS_START = 'UPDATE_USER_DETAILS_START';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_DETAILS_ERROR = 'UPDATE_USER_DETAILS_ERROR';

export const LOGOUT = 'LOGOUT';

export const REGISTER_INDIVIDUAL_START = 'REGISTER_INDIVIDUAL_START';
export const REGISTER_INDIVIDUAL = 'REGISTER_INDIVIDUAL';
export const REGISTER_INDIVIDUAL_ERROR = 'REGISTER_INDIVIDUAL_ERROR';

export const REGISTER_FAMILY_START = 'REGISTER_FAMILY_START';
export const REGISTER_FAMILY = 'REGISTER_FAMILY';
export const REGISTER_FAMILY_ERROR = 'REGISTER_FAMILY_ERROR';

export const GET_LOGGED_USER_START = 'GET_LOGGED_USER_START';
export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const GET_LOGGED_USER_ERROR = 'GET_LOGGED_USER_ERROR';
