export const GET_TRANSACTIONS_START = 'GET_TRANSACTIONS_START';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';

export const REFRESH_TRANSACTIONS_START = 'REFRESH_TRANSACTIONS_START';
export const REFRESH_TRANSACTIONS = 'REFRESH_TRANSACTIONS';
export const REFRESH_TRANSACTIONS_ERROR = 'REFRESH_TRANSACTIONS_ERROR';
