const NAVIGATORS = {
  AUTH: 'AUTH',
  MAIN: 'MAIN',
  SETTINGS: 'SETTINGS',
  TRANSACTIONS: 'TRANSACTIONS',
  DASHBOARD: 'DASHBOARD',
  CATEGORIES: 'CATEGORIES',
  TAGS: 'TAGS',
  USERS: 'USERS',
};

export default NAVIGATORS;
