const SCREENS = {
  DASHBOARD: 'DASHBOARD',
  LOGIN: 'LOGIN',
  REGISTRATION: 'REGISTRATION',
  TRANSACTIONS: 'TRANSACTIONS',
  LOADING: 'LOADING',
  SETTINGS: 'SETTINGS',
  NOTIFICATIONS_SETTINGS: 'NOTIFICATIONS_SETTINGS',
  LANGUAGE_SETTINGS: 'LANGUAGE_SETTINGS',
  CATEGORIES: 'CATEGORIES',
  TAGS: 'TAGS',
  USERS: 'USERS',
};

export default SCREENS;
