const SCREENS = {
  EDIT_USER_DETAILS: 'EDIT_USER_DETAILS',
  DASHBOARD: 'DASHBOARD',
  LOGIN: 'LOGIN',
  ACCOUNT_SELECT: 'ACCOUNT_SELECT',
  TRANSACTIONS: 'TRANSACTIONS',
  LOADING: 'LOADING',
  SETTINGS: 'SETTINGS',
  NOTIFICATIONS_SETTINGS: 'NOTIFICATIONS_SETTINGS',
  LANGUAGE_SETTINGS: 'LANGUAGE_SETTINGS',
  CATEGORIES: 'CATEGORIES',
  TAGS: 'TAGS',
  INVITATIONS: 'INVITATIONS',
  ACCOUNT_USERS: 'ACCOUNT_USERS',
};

export default SCREENS;
