export const ADD_INVITATION_START = 'ADD_INVITATION_START';
export const ADD_INVITATION = 'ADD_INVITATION';
export const ADD_INVITATION_ERROR = 'ADD_INVITATION_ERROR';

export const DELETE_INVITATION_START = 'DELETE_INVITATION_START';
export const DELETE_INVITATION = 'DELETE_INVITATION';
export const DELETE_INVITATION_ERROR = 'DELETE_INVITATION_ERROR';

export const GET_INVITATION_START = 'GET_INVITATION_START';
export const GET_INVITATION = 'GET_INVITATION';
export const GET_INVITATION_ERROR = 'GET_INVITATION_ERROR';
