export const UPDATE_LOCALE_START = 'UPDATE_LOCALE_START';
export const UPDATE_LOCALE = 'UPDATE_LOCALE';
export const UPDATE_LOCALE_ERROR = 'UPDATE_LOCALE_ERROR';

export const UPDATE_USER_DETAILS_START = 'UPDATE_USER_DETAILS_START';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_DETAILS_ERROR = 'UPDATE_USER_DETAILS_ERROR';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER = 'GET_USER';
export const GET_USER_ERROR = 'GET_USER_ERROR';
