export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const REFRESH_CATEGORIES_START = 'REFRESH_CATEGORIES_START';
export const REFRESH_CATEGORIES = 'REFRESH_CATEGORIES';
export const REFRESH_CATEGORIES_ERROR = 'REFRESH_CATEGORIES_ERROR';

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';

export const EDIT_CATEGORY_START = 'EDIT_CATEGORY_START';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR';

export const GET_CATEGORY_START = 'GET_CATEGORY_START';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';
