export const GET_INVITATIONS_START = 'GET_INVITATIONS_START';
export const GET_INVITATIONS = 'GET_INVITATIONS';
export const GET_INVITATIONS_ERROR = 'GET_INVITATIONS_ERROR';

export const REFRESH_INVITATIONS_START = 'REFRESH_INVITATIONS_START';
export const REFRESH_INVITATIONS = 'REFRESH_INVITATIONS';
export const REFRESH_INVITATIONS_ERROR = 'REFRESH_INVITATIONS_ERROR';
