export const GET_ACCOUNTS_START = 'GET_ACCOUNTS_START';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR';

export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';
